project: 
  title: "マヨヒガ研究所"
  type: website
  execute-dir: project
  output-dir: docs
  preview: 
    port: 8080
    browser: false

execute: 
  freeze: auto
  cache: true

website: 
  title: マヨヒガ研究所
  favicon: images/profile.png
  image: images/profile.png
  search:
    location: navbar
    type: textbox
  navbar:
    logo: images/profile.png
    left: 
      - qmds/index.qmd
      - qmds/posts.qmd
      - qmds/about.qmd
      - qmds/contact.qmd
    tools:
      - icon: github
        menu:
          - text: Source code
            href: https://github.com/yasuih777/MayohigaLab
          - text: Issues page
            href: https://github.com/yasuih777/MayohigaLab/issues
  page-footer: Copyright 2025 
  cookie-consent:
    type: express
    style: headline
  google-analytics:
    tracking-id: "G-8DYYPDLKN5"
    anonymize-ip: true

title: Non title
date: now
date-modified: now
date-format: iso
order: 0
link-external-icon: true
link-external-newwindow: true
format:
  html:
    theme: minty
    css: styles.css
    grid:
      body-width: 1440px
      gutter-width: 10px
    linestretch: 2em
    toc: true
    anchor-sections: true
    smooth-scroll: true
    quarto-required: ">= 1.6.40"

code-line-numbers: true
code-annotations: hover
code-fold: true

license: CC BY 4.0 DEED
