services:
  web-source:
    build: .
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - ./:/web_source
    working_dir: /web_source
    command:
      # /bin/bash 
      /bin/bash --login