---
title: ウイルス感染症の数理シミュレーション（応用）
date: now
categories:
    - Julia
    - Simulation
notebook-view:
  - notebook: simulation.ipynb
    title: "補足資料"
format:
  html:
    other-links:
      - text: ウイルス感染症の数理シミュレーション（基礎）
        href: ../20250209_virus_simulation_1/index.html
draft: true
---

[ウイルス感染症の数理シミュレーション（基礎）](../20250209_virus_simulation_1/index.html)では、ウイルスを細胞間の相互作用を考慮したモデルを作成し、ウイルス量と細胞数に関する動態を確認した。今回は、特異的な特性をもつウイルスに焦点を当てて、それらの数理モデルや動態を確認していく。

# B型感染ウイルスの動態

B型感染ウイルス(hepatities B virus: HBV)はヒト肝細胞を標的とするウイルスである。このウイルスは乳児期にワクチン接種を行うことで高い確率で予防できるが、感染後には有効な薬剤が少なく、慢性化すると肝硬変や肝がんの原因になる。

HBVウイルスは細胞→核内に侵入した後、cc-cDNA(convalenty closed circular DNA)という安定した二本鎖DNAに変異し、これを起点に新たなウイルス増殖を行うため、完全に排除することが非常に難しい。

即ち、HBVウイルスの予防には細胞への侵入を防止することが最も重要である。そこで、HBVウイルスの侵入状態ごとの動態を数理モデルでシミュレーションすれば感染阻害が形成される条件を解析することができる。

HBVウイルスの各侵入状態${V_{dis}, V_{att}, V_{int}, V_{ccc}}$は**反応速度論**を用いた常微分方程式で記述できる。

::: {.callout-note title="反応速度論"}
一般的な可逆化学反応(A⇔B)による生成物の組成動態は以下の微分方程式で表現できる。

```{dot}
//| fig-width: 2
//| fig-height: 0.5

digraph G {
    graph [rankdir = LR]
    A;
    B;

    A -> B [label="kB"]
    B -> A [label="kA"]
}
```

$$
\begin{align}
&\frac{\partial |A|}{\partial t} = k_A |B| - k_B |A| \\
&\frac{\partial |B|}{\partial t} = k_B |A| - k_A |B|
\end{align}
$$
:::

## 細胞侵入に着目したモデル

まずは、HBVウイルス動態についてウイルスが細胞から解離しているか、接着しているかの単純な数理モデルを考える。

```{dot}
//| fig-width: 4
//| fig-height: 1

digraph G {
    graph [rankdir = LR]
    dis [label="V(dis)"];
    att [label="V(att)"];

    dis -> att [label="k(att)"]
    att -> dis [label="k(dis)"]
}
```

これは、上記の可逆化学反応における微分方程式と同じ表現で記述できる。@eq-HBV-middle

- $V_{dis}(t)$: 1細胞あたりの解離ウイルス量
- $V_{att}(t)$: 1細胞あたりの接着ウイルス量
- $k_{dis}$: 1細胞あたりのウイルス解離速度
- $k_{att}$: 1細胞あたりのウイルス接着速度

$$
\begin{align}
&\frac{\partial V_{dis}(t)}{\partial t} = k_{dis} V_{att}(t) - k_{att} V_{dis}(t) \\
&\frac{\partial V_{att}(t)}{\partial t} = k_{att} V_{dis}(t) - k_{dis} V_{att}(t)
\end{align}
$$ {#eq-HBV-middle}

これらの動態は以下のようになる。一般的にウイルスが解離する速度が速いため、$V_{dis}$量が多くなり、解が収束する。

{{< embed simulation.ipynb#fig-HBV-middle >}}

::: {.callout-note}
@eq-HBV-middle のような単純な可逆反応を表す連立常微分方程式は固有値$\lambda = 0$を持つため、一般解は以下のようになる。このとき、$t \rightarrow \infty$で$C_{1} e^{- \lambda t} \rightarrow 0$なので、解は必ず収束する。

$$
\left\{ \,
\begin{aligned}
&V_{dis} = \alpha_{1} C - C_{1} e^{- \lambda t} \\
&V_{att} = C_{1} e^{- \lambda t} + \alpha_{2} C
\end{aligned}
\right.
$$
:::

## 全状態を考慮したモデル

次に、全状態を考慮したモデルを以下の微分方程式 @eq-HBV-all で仮定する。

```{dot}
//| fig-width: 8
//| fig-height: 2

digraph G {
    graph [rankdir = LR]
    dis [label="V(dis)"];
    att [label="V(att)"];

    subgraph cluster_cell {
        label = "Cell";

        int [label="V(int)"];
        intout [label="", shape=point, color=none, width=0.01, height=0.01];

        subgraph cluster_nucleus {
            label = "Nucleus"

            ccc [label="V(ccc)"];
            cccout [label="", shape=point, color=none, width=0.01, height=0.01];
        }

        int -> intout [label="k(di)"]
    }

    dis -> att [label="k(att)"]
    att -> dis [label="k(dis)"]
    att -> int [label="k(int)"]
    int -> ccc [label="k(ccc)"]
    ccc -> cccout [label="k(dc)"]
}
```

- $V_{dis}(t)$: 1細胞あたりの解離ウイルス量
- $V_{att}(t)$: 1細胞あたりの接着ウイルス量
- $V_{int}(t)$: 1細胞あたりの内在化ウイルス量
- $V_{ccc}(t)$: 1細胞あたりのcccDNA量
- $k_{dis}$: 1細胞あたりのウイルス解離速度
- $k_{att}$: 1細胞あたりのウイルス接着速度
- $k_{int}$: 1細胞あたりのウイルス内在化速度
- $k_{ccc}$: 1細胞あたりのcccDNA形成速度
- $k_{di}$: 1細胞あたりの内在化ウイルス分解速度
- $k_{dc}$: 1細胞あたりのcccDNA分解速度
- $K$: 1細胞あたりのcccDNA量最大値（環境収容力）

$$
\begin{align}
&\frac{\partial V_{dis}(t)}{\partial t} = k_{dis} V_{att}(t) - k_{att} V_{dis}(t) \\
&\frac{\partial V_{att}(t)}{\partial t} = k_{att} V_{dis}(t) - k_{dis} V_{att}(t) - k_{int} V_{att}(t) \\
&\frac{\partial V_{int}(t)}{\partial t} = k_{int} V_{att}(t) - k_{ccc} \left(1 - \frac{V_{ccc}(t)}{K} \right) V_{int}(t) - k_{di} V_{int}(t) \\
&\frac{\partial V_{ccc}(t)}{\partial t} = k_{ccc} \left(1 - \frac{V_{ccc}(t)}{K} \right) V_{int}(t) - k_{dc} V_{ccc}(t) \\
\end{align}
$$ {#eq-HBV-all}

これらの動態は以下のようになる。解離ウイルスの増加および接着ウイルスの減少が確認できるが、cccDNA量も環境収容力まで増加しておりウイルス感染していることが分かる。

{{< embed simulation.ipynb#fig-HBV-all >}}

これらの数理モデリングでは、各パラメータを変化させることで最終的な動態を比較することができる。このHBVウイルスのcccDNA量を減らすために、各反応速度を抑制する阻害薬と投与した場合に最終的なcccDNA量がどうなるかを検証する。

ウイルス接着速度$k_{att}$、ウイルス内在化速度$k_{int}$、cccDNA速度形成速度$k_{ccc}$をそれぞれ独立に$\alpha$%阻害する仮定において、最終(反応開始後12日)cccDNA量は以下のようになる。

低い阻害率においては状態が近い内在化阻害よりも接着阻害の方がより効果があることが分かった。

{{< embed simulation.ipynb#fig-HBV-inhibition >}}

# 参考
- [ウイルス感染の数理モデルとシミュレーション](https://www.kyoritsu-pub.co.jp/book/b10044853.html)
- [Overview of Julia's SciML/Build and run your first simulation with Julia's SciML](https://docs.sciml.ai/Overview/stable/getting_started/first_simulation/)