---
title: "ホーム"
date: 01-26-2025
---

# このサイトについて
管理者が興味があることを書いていきます。

- 統計理論の検証
- 数値シミュレーション
- 学習の忘備録

などなど

---

# 免責事項

- 本サイトに掲載されている情報は、正確である保証はありません。
- 本サイトに掲載されている情報は、私個人の見解である。所属機関を代表する見解ではありません。
- 本サイトを利用して、あなたに損害が生じても、一切責任を負いません。
- 本サイトのコンテンツは、予告なく変更や公開の取り消しする場合があります。

---

# プライバシーポリシー

## GA4

当サイトでは、Googleによるアクセス解析ツール「Googleアナリティクス」を使用しています。このGoogleアナリティクスはデータの収集のためにCookieを使用しています。このデータは匿名で収集されており、個人を特定するものではありません。

この機能はCookieを無効にすることで収集を拒否することが出来ますので、お使いのブラウザの設定をご確認ください。この規約に関しての詳細は[Googleアナリティクスサービス利用規約](https://marketingplatform.google.com/about/analytics/terms/jp/)のページや[Googleポリシーと規約ページ](https://policies.google.com/technologies/ads?hl=ja)をご覧ください。

## お問い合わせフォーム

[お問合せページ](./contact.qmd)はGoogle Formを使用しています。Google Formの機能でお問い合わせの記録の際にメールアドレスを収集しています。これは返信のみに利用し、他の用途で使用することはありません。予めご了承ください。

---

# ライセンス

## ブログ内のコンテンツ
本サイトにおける各エントリの文章や画像などのコンテンツは[クリエイティブ・コモンズ・ライセンス](https://creativecommons.org/licenses/by/4.0/deed.ja)を適応します。

## ブログ内サンプルコードのライセンス
ブログ内で書いているコードに関しては例外的にMIT Licenceを適応します。

:::{.callout-note collapse="true"}
## MIT License

Copyright 2025

以下に定める条件に従い、本ソフトウェアおよび関連文書のファイル（以下「ソフトウェア」）の複製を取得するすべての人に対し、ソフトウェアを無制限に扱うことを無償で許可します。これには、ソフトウェアの複製を使用、複写、変更、結合、掲載、頒布、サブライセンス、および/または販売する権利、およびソフトウェアを提供する相手に同じことを許可する権利も無制限に含まれます。

上記の著作権表示および本許諾表示を、ソフトウェアのすべての複製または重要な部分に記載するものとします。

ソフトウェアは「現状のまま」で、明示であるか暗黙であるかを問わず、何らの保証もなく提供されます。ここでいう保証とは、商品性、特定の目的への適合性、および権利非侵害についての保証も含みますが、それに限定されるものではありません。 作者または著作権者は、契約行為、不法行為、またはそれ以外であろうと、ソフトウェアに起因または関連し、あるいはソフトウェアの使用またはその他の扱いによって生じる一切の請求、損害、その他の義務について何らの責任も負わないものとします。
:::